const endpoints = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    me: "/profile/me",
    heartbeat: "/auth/heartbeat",
    otpRequest: "/auth/otp/request",
    otpVerify: "/auth/otp/verify",
    resetPassword: "/auth/reset-password",
    forgotPassword: "/auth/forgot-password",
  },
  admin: {
    stats: "/admin/dashboard/stats",
    overview: "/admin/dashboard/overview",
    users: "/admin/users",
    students: "/admin/students",
    instructors: "/admin/instructors",
    courses: "/admin/courses",
    classes: "/admin/classes",
    exams: "/admin/exams",
    enrollments: "/admin/enrollments",
    financials: "/admin/financials",
    coupons: "/admin/coupons",
    certificates: "/admin/certificates",
    payouts: "/admin/payouts",
    cms: "/admin/cms",
    settings: "/admin/settings",
    sections: "/admin/sections",
    auditLogs: "/admin/audit-logs",
    roles: "/admin/roles",
    permissions: "/admin/permissions",
    subscriptionPlans: "/admin/subscription-plans",
    reviewQueue: "/admin/courses/review-queue",
    tickets: "/admin/tickets",
    integrations: "/admin/integrations",
    categories: "/admin/categories",
    homework: "/admin/homework",
    courseStaff: (courseId) => `/admin/courses/${courseId}/staff`,
    courseSubmitReview: (courseId) => `/admin/courses/${courseId}/submit-review`,
    courseApprove: (courseId) => `/admin/courses/${courseId}/approve`,
    courseReject: (courseId) => `/admin/courses/${courseId}/reject`,
    userSessions: (userId) => `/admin/users/${userId}/sessions`,
    userDevices: (userId) => `/admin/users/${userId}/devices`,
    userPermissions: (userId) => `/admin/users/${userId}/permissions`,
    forceLogout: (userId) => `/admin/users/${userId}/sessions`,
    payoutPaid: (payoutId) => `/admin/payouts/${payoutId}/paid`,
  },
  instructorDashboard: {
    overview: "/instructor/dashboard/overview",
  },
  instructor: {
    classes: "/instructor/classes",
    courses: "/instructor/courses",
    students: "/instructor/students",
    performance: "/instructor/performance",
    availability: "/instructor/availability",
    exams: "/instructor/exams",
    wallet: "/instructor/wallet",
    qna: "/instructor",
  },
  student: {
    qna: "/student",
    myCourses: "/student/courses/my-courses",
    financialsMyCourses: "/student/financials/my-courses",
    financialsCheckoutCourse: (courseId) => `/student/financials/checkout/course/${courseId}`,
    financialsCheckoutPrivate: (availabilityId) => `/student/financials/checkout/private/${availabilityId}`,
    courseUnits: (courseId) => `/student/courses/${courseId}/units`,
    exams: "/student/exams",
    exam: (examId) => `/student/exams/${examId}`,
    examStart: (examId) => `/student/exams/${examId}/start`,
    examSubmit: (examId) => `/student/exams/${examId}/submit`,
    examResults: (examId, submissionId) => `/student/exams/${examId}/results/${submissionId}`,
    progressCompletedLessons: (courseId) => `/student/progress/courses/${courseId}/completed-lessons`,
    progressStats: (courseId) => `/student/progress/courses/${courseId}/stats`,
    progressResume: (courseId) => `/student/progress/courses/${courseId}/resume`,
    progressLessonAccess: (lessonId) => `/student/progress/lessons/${lessonId}/access`,
    progressLessonComplete: (lessonId) => `/student/progress/lessons/${lessonId}/complete`,
    lessonResources: (lessonId) => `/student/lessons/${lessonId}/resources`,
    bookingsAvailable: "/student/bookings/available-slots",
    bookSlot: (availabilityId) => `/student/bookings/${availabilityId}/book`,
    classes: "/student/classes",
    couponValidate: "/student/coupons/validate",
  },
  homework: {
    mine: "/homework/student/mine",
    assignment: (homeworkId) => `/homework/student/assignments/${homeworkId}`,
    cohortList: (cohortId) => `/homework/student/cohort/${cohortId}`,
    submit: (homeworkId) => `/homework/student/${homeworkId}/submit`,
    instructorPending: "/homework/instructor/pending-submissions",
    submissionReviewStatus: (submissionId) =>
      `/homework/instructor/submissions/${submissionId}/review-status`,
    gradeSubmission: (submissionId) => `/homework/instructor/submissions/${submissionId}/grade`,
  },
  notifications: "/notifications",
  public: {
    courses: "/courses",
    packages: "/packages",
    posts: "/public/posts",
    post: (slug) => `/public/posts/${encodeURIComponent(slug)}`,
    siteSettings: "/public/settings",
  },
};

export default endpoints;
